### ISSUE TITLE
Don't use while(true)

### ISSUE THREAD

**Issue by bokherus** [OOP2018/guessing-game-Driveiei#2]
Consider using a boolean returned from `game.guess(number)` and break the loop once it's guessed correctly to avoid infinite loop.

**Comment by Driveiei** [comment]
Already fixed now. Thank you.

**Comment by Driveiei** [comment]
should I close the issues when I already fixed???

**Comment by bokherus** [comment]
Yes, but make sure you actually resolve the issue. If you're not sure mention any TAs to check your commits.
